name: Обновление гиста

on: push

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest 
    steps:
    - name: Получение репозитория
      uses: actions/checkout@v3

    - name: Обновление гиста
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: ${{ vars.ID }}
        file_path: resume.yaml
